# fly.toml app configuration file generated for lingering-cloud-2308 on 2023-09-15T15:03:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lingering-cloud-2308"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
